version: '3.8'

services:
  db:
    image: mysql:8.1.0
    container_name: db
    restart: always
    volumes:
      - /mysql:/var/lib/mysql
    hostname: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_INITDB_SKIP_TZINFO="yes"
    ports:
      - "3312:3306"